### PR TITLE
Agenda

### PR DESCRIPTION
**Pull request by jmak**

### CODE REVIEW

**Comment by lukaszklis** [comment]
Hi @jmak, thanks for your PR! It seems however, that the agenda you added was from the 37th meet.js Katowice meet up (relevant commit introducing the change in Katowice’s repository: https://github.com/meetjspl/katowice/commit/7a1ddc4d83784f4e462de0f78ade92561f7684df). 

meet.js Summit is an annual event ran in English and IIRC, we still don’t have an agenda to share.

cc @meetjspl/collaborators

**Comment by jsynowiec** [comment]
@lukaszklis why didn't you ask us (this year's Summit organisers) before hitting that close button? :) Everything's fine, we're preparing the website agenda because CFP is going to end soon. Maciej just used our last local meetup as reference and placeholder data, so we could review how it looks.

**Comment by lukaszklis** [comment]
@jsynowiec sorry, it seems like I lost access to the comms tool (hence the ping). :( Will double check next time.

**Comment by jsynowiec** [comment]
@jmak Please resolve conflicts when you have time. I want to continue with the agenda next week.

**Comment by jmak** [comment]
@jsynowiec Done. Conflicts have been resolved.

**Pull request merged**
