### PR TITLE
Remove the bitmap from ECS vector graphic 

### PR DESCRIPTION
**Pull request by thymikee**
Basically removed almost invisible (even under zoom-in) bitmap from `gdansk-zuraw.svg`. Saved 190kB

### CODE REVIEW

**Review by lukaszklis — COMMENTED** [review]
Could you add it also as a task for gulp? We might have more SVGs in the future and not everyone has `svgo` installed. :)

**Comment by thymikee** [comment]
Oh, I can see that SVGs are already handled with `gulp-imagemin` https://github.com/sindresorhus/gulp-imagemin#imageminplugins-options. Double checked and it works well. Adding uniminified SVGs then, thanks @lukaszklis!

**Comment by typeofweb** [comment]
Weird, I was sure all svg were optimised through SVGOMG :)

**Comment by lukaszklis** [comment]
@thymikee @mmiszy I’d close this PR since the only difference it makes, it removes the padding around the crane. :)

In case you want to merge it, please adjust the title, so it would actually summarize what is happening here.

**Comment by thymikee** [comment]
It's not the padding but almost invisible bitmap that you don't see. Look at the size comparison, I've summarized it in PR description.

**Comment by thymikee** [comment]
Renamed.

**Comment by lukaszklis** [comment]
@thymikee ah, true that. LGTM 👍

**Review by lukaszklis — APPROVED** [review]

**Pull request merged**
